version: '3.9'

services:

  admin:
    container_name: 'kavaleridze-admin-ui'
    build:
      context: kavaleridze-admin/.
      args:  
        - SERVER_URL=http://127.0.0.1:8081/api
    environment:
      NODE_ENV: 'production'
    ports:
      - '5174:80'
    depends_on:
      - api
    restart: on-failure


  web:
    container_name: 'kavaleridze-web-ui'
    build: kavaleridze/.
    environment:
      VITE_SERVER_URL: 'http://localhost:8081'
    ports:
      - '8080:8080'
    depends_on:
      - api
    restart: on-failure
  
  api:
    container_name: 'kavaleridze-api-server'
    build: kavaleridze-backend/.
    environment:
      SPRING_DATA_REDIS_HOST: redis
      MAIL_USER: 'museum_kav_dev@meta.ua'
      MAIL_PASSWORD: '!MUS!&2023!kav'
    ports:
      - '8081:8080'
    depends_on:
      - redis
    restart: on-failure

  redis:
    container_name: 'kavaleridze-db'
    image: 'redis/redis-stack:7.2.0-v0'
    ports:
      - '8001:8001'
    restart: on-failure
