version: '3.9'

services:

  admin:
    container_name: 'kavaleridze-admin-ui'
    build: kavaleridze-admin/.
    environment:
      SERVER_URL: http://localhost:8081/api
    ports:
      - '5174:80'
    depends_on:
      - api
    restart: on-failure

  redis:
    container_name: 'kavaleridze-db'
    image: 'redis/redis-stack:7.2.0-v0'
    ports:
      - '8001:8001'
    restart: on-failure
