version: '3.9'

services:
  
  api:
    container_name: 'museum-api-server'
    build: museum-back/.
    environment:
      SPRING_DATA_REDIS_HOST: redis
      MAIL_USER: 'museum_kav_dev@meta.ua'
      MAIL_PASSWORD: '!MUS!&2023!kav'
      ORIGIN_URI: '127.0.0.1'
    ports:
      - '8081:8080'
    depends_on:
      - redis
    restart: on-failure

  redis:
    container_name: 'museum-db'
    image: 'redis/redis-stack:7.2.0-v0'
    ports:
      - '8001:8001'    
    environment:
      REDIS_ARGS: '--appendonly yes'
    volumes:
      - redis_data:/data
    restart: on-failure
    
volumes:
  redis_data:
